### PR TITLE
Fix ruida rasterizable

### LINKED ISSUE #187: Engrave with Ruida driver goes wild
Seen with 
VisiCut		 Version: 1.9-169-g99244adc
LibLaserCut	 Version: visicut1.7
on Ubuntu 22.04 
using Model: Ruida	 Driver:de.thomas_oster.liblasercut.drivers.Ruida

I am loading this PNG image into visicut, scale it to 6 cm x 5.6 cm.
Engrave profile, with default 500dpi, floyd steinberg, Grayscale shift 0, not inverted colors.
Use bidirectional rastering [x]
min power 20, max power 20, speed 100.

schickard_portrait

I'd expect engraving line by line with even speed and some reasonable overshoot on both sides.
I see jerky movement, decelerating and accelerating in mid flight, no overshoot at the sides, with some occasional diagonal and vertical movements. 

https://user-images.githubusercontent.com/1108546/212476800-fdbe92cb-5358-44f9-8c87-d73b8b98f142.mp4

The attached zip contains a .rd file saved from such an attempt.
[schickard.zip](https://github.com/t-oster/LibLaserCut/files/10417906/schickard.zip)

### PR DESCRIPTION
**Pull request by kkaempf**
Fixes #187

### CODE REVIEW

**Comment by jnweiger** [comment]
Here you are: https://github.com/t-oster/LibLaserCut/issues/187

File: src/main/java/de/thomas_oster/liblasercut/FloatMinMaxPowerSpeedFrequencyProperty.java [hunk 1]
```diff
@@ -88,11 +90,33 @@ public Object getProperty(String name)
...
+  /**
+   * Must override since parent class only allows 0 < speed < 100
+   * 
+   */
+
+  @Override
+  public void setSpeed(float speed)
+  {
+    speed = speed < 0 ? 0 : speed;
+    speed = speed > 1000 ? 1000 : speed;
```
Comment (mgmax) [inline src/main/java/de/thomas_oster/liblasercut/FloatMinMaxPowerSpeedFrequencyProperty.java:110]: All speed settings for all other lasercutters are in percent, maximum 100. So this one should be the same for consistency. If we support absolute speeds or other units (mm/s, inch per whatever) one day, then this should be one consistent interface for all/most lasercutters, see https://github.com/t-oster/VisiCut/issues/381

File: src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java [hunk 2]
```diff
@@ -180,6 +182,36 @@ public boolean canEstimateJobDuration()
     return false;
   }
 
+  /**
+   * 'runway' for laser to get up to speed when rastering (in mm)
+   *
+   */
+  private double rasterPadding = 20;
```
Comment (mgmax) [inline src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java:189]: Please double-check if this is initialized correctly when loading old settings that do not yet have this property. As far as I remember, XStream sets all missing fields to zero/false/null, ignoring the default value. You may need to implement it similar to here (`Double` instead of `double` datatype, then a missing initialization will be `null` and can be distinguished from `0`). https://github.com/t-oster/LibLaserCut/blob/5215383458060acb7404d01356a2a8af0137f52c/src/main/java/de/thomas_oster/liblasercut/drivers/GenericGcodeDriver.java#L1098-L1104

File: src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java [hunk 3]
```diff
@@ -92,6 +92,8 @@ public class Ruida extends LaserCutter
   protected static final String SETTING_BED_WIDTH = "Bed width (mm)";
   protected static final String SETTING_BED_HEIGHT = "Bed height (mm)";
   protected static final String SETTING_USE_BIDIRECTIONAL_RASTERING = "Use bidirectional rastering";
+  protected static final String SETTING_RASTER_PADDING = "Padding per raster line (mm)";
+  protected static final String SETTING_RASTER_OUTSIDE = "Allow padding outside of specs";
```
Comment (mgmax) [inline src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java:96]: should be the same texts as in https://github.com/t-oster/LibLaserCut/blob/5215383458060acb7404d01356a2a8af0137f52c/src/main/java/de/thomas_oster/liblasercut/drivers/GenericGcodeDriver.java#L109-L110 unless there is a very good reason. If the other text is not good, feel free to change both.

**Review by mgmax — COMMENTED** [review]
Nice to hear from you! I have some feedback, maybe it helps, maybe not ;-)

**Comment by jnweiger** [comment]
Ah, historical ballast. Sorry. My original driver (as located in the private fork) used absolute values mm/sec.

I understand the consistency argument within visicut. But the same argument can be applied to ruida settings across visicut, lightburn, and rdworks. Both, lightburn and rdworks use mm/sec, so making it percent in visicut makes it inconsistent there.

**Comment by mgmax** [comment]
> Both, lightburn and rdworks use mm/sec, so making it percent in visicut makes it inconsistent there.

Of course the UI should offer both in the future.  Until then, a local hack in one single driver will just cause confusion.
Currently, there is no proper API for absolute values (get units to show in the UI, conversion between abs. and percent).

**Comment by kkaempf** [comment]
https://github.com/t-oster/LibLaserCut/pull/186/commits/01b069ebf5d72fc3663f1b431533c30085bc7938 🤷🏻‍♂️ 😆

File: src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java (hunk 2 above)
Comment (kkaempf) [reply src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java:189]: ✅

**Comment by kkaempf** [comment]
Tests were successful, marking "ready for review". Thanks ! 🙏🏻

File: src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java (hunk 2 above)
Comment (mgmax) [reply src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java:189]: As far as I understand, the type should be `Double` not `double`. `Double` can be `null` (like null-pointer), `double` is just a value.

Please check that
- old settings that don't have the value are not loaded as 0 but as 20 (due to the `null` trick).
- in new settings, you can set the value to 0, save it, restart VisiCut, and it still remains at 0.

I'd be surprised if the current code actually works in all these cases.

**Review by mgmax — CHANGES_REQUESTED** [review]

File: src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java (hunk 2 above)
Comment (kkaempf) [reply src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java]: `double` -> `Double` ✅

Comment (jnweiger) [reply src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java]: This uppercase D in Double causes compile errors:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project liblasercut: Compilation failure: Compilation failure: 
[ERROR] /home/testy/src/github/kkaempf/LibLaserCut/src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java:[189,34] incompatible types: int cannot be converted to java.lang.Double
[ERROR] /home/testy/src/github/kkaempf/LibLaserCut/src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java:[192,17] getRasterPadding() in de.thomas_oster.liblasercut.drivers.Ruida cannot override getRasterPadding() in de.thomas_oster.liblasercut.LaserCutter
[ERROR]   return type java.lang.Double is not compatible with double
[ERROR] /home/testy/src/github/kkaempf/LibLaserCut/src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java:[191,3] method does not override or implement a method from a supertype
[ERROR] /home/testy/src/github/kkaempf/LibLaserCut/src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java:[193,48] incompatible types: int cannot be converted to java.lang.Double
[ERROR] -> [Help 1]

**Review by mgmax — APPROVED** [review]
looks good. I'll merge soon if there are no further comments.

File: src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java (hunk 2 above)
Comment (mgmax) [reply src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java]: @kkaempf has this been fixed?
It should be enough to change the type the property but leave the functions unchanged.

**Review by mgmax — CHANGES_REQUESTED** [review]
Please clarify the comment by @jnweiger .
Did you test two the mentioned cases regarding loading of settings?

**Comment by jnweiger** [comment]
I can compile with this additional patch:

```
--- a/src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java
+++ b/src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java
@@ -186,11 +186,11 @@ public class Ruida extends LaserCutter
    * 'runway' for laser to get up to speed when rastering (in mm)
    *
    */
-  private Double rasterPadding = 20;
+  private Double rasterPadding = 20.;
 
   @Override
-  public Double getRasterPadding() {
-    if (rasterPadding == null) rasterPadding = 20;
+  public double getRasterPadding() {
+    if (rasterPadding == null) rasterPadding = 20.;
     return rasterPadding;
   }
```

File: src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java (hunk 2 above)
Comment (kkaempf) [reply src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java]: Just merged @jnweiger's PR kkaempf/LibLaserCut#3

File: src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java [hunk 4]
```diff
@@ -941,6 +982,10 @@ public void setProperty(String attribute, Object value) {
       this.setBedWidth((Double)value);
     } else if (SETTING_USE_BIDIRECTIONAL_RASTERING.equals(attribute)) {
       this.setUseBidirectionalRastering((Boolean) value);
+    } else if (SETTING_RASTER_PADDING.equals(attribute)) {
+      this.setRasterPadding((Double) value);
+    } else if (SETTING_RASTER_OUTSIDE.equals(attribute)) {
```
[the remark this answers is not in the document]
Comment (kkaempf) [reply src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java:987]: Using upstream standard

**Comment by mgmax** [comment]
Code looks good.
Did you test the two cases I asked about earlier?

**Comment by kkaempf** [comment]
> Did you test the two cases I asked about earlier?

Sorry no. And I wouldn't even know how.

Maybe @jnweiger can answer this ? 🤔

**Comment by jnweiger** [comment]
I've done the following test:

* Install deb package visicut-1.9-171-ga45332c3
* start `/usr/bin/visicut`
* Create a 'Nova 35 fablabbg' device with the Ruida driver.
* Load an example svg, select 'cut all'
* Create some settings:
  - 3mm cut: minPower=33% maxPower=80% speed=50% freq=500
  - 4mm cut: minPower=44% maxPower=80% speed=40% freq=500
  - 5mm cut: minPower=55% maxPower=80% speed=30% freq=500
* Send to file with the 3mm setting.

Then compile github/t-oster/Visicut master with this github/kkaempf/LibLasercut fix-ruida-rasterizable 
* start `java -Xms256m -Xmx1024m -jar target/visicut-*-full.jar`
* Load an example svg,  select 'cut all'
* Inspect the settings:
    - 3mm cut: minPower=33% maxPower=80% speed=0% freq=500
    - 4mm cut: minPower=44% maxPower=80% speed=0% freq=500
    - 5mm cut: minPower=55% maxPower=80% speed=0% freq=500

The speeds all show 0.
Retesting with /usr/bin/visicut shows that the speeds were correctly saved.

**Comment by jnweiger** [comment]
The second test works fine:

* with target/visicut-1.9-SNAPSHOT-full.jar change the minpower of the 5mm setting to 0.
* exit visicut, restart.
* the setting show up as 0 as expected.

**Comment by jnweiger** [comment]
@mgmax what needs to be done here to get it merged?
I'd be much more comfortable to have a working visicut first, and then fix the details about using the correct 'double' datatype later.
Currently this PR blocks us completely from using visicut at the lab.

**Comment by mgmax** [comment]
The only thing I am strict about here is that old settings (lasercutter device settings, material power/speed, ...) created using an old *mainline* VisiCut version still work in the new version. This includes that default values for variables that did not exist before this PR are initialized correctly. I don't care about compatibility with custom forks.

The XStream serializer we use has a bug/misfeature that if you define `class myClass { double foo = 123; }` and load an XML file that does not contain `foo` (e.g. from an older Visicut version) then you will get `foo=0`. Therefore the `Double` workaround is needed.

I agree that the sonatype check is only a warning and not relevant here.

File: src/main/java/de/thomas_oster/liblasercut/FloatMinMaxPowerSpeedFrequencyProperty.java [hunk 5]
```diff
@@ -31,6 +31,7 @@
 public class FloatMinMaxPowerSpeedFrequencyProperty extends FloatPowerSpeedFrequencyProperty {
 
   private float min_power = 10.0f;
+  private float speed = 500.0f;
```
Comment (mgmax) [inline src/main/java/de/thomas_oster/liblasercut/FloatMinMaxPowerSpeedFrequencyProperty.java:34]: Loading the speed from old settings does not work correctly for me. I guess this line should be removed.

**Review by mgmax — CHANGES_REQUESTED** [review]

File: src/main/java/de/thomas_oster/liblasercut/FloatMinMaxPowerSpeedFrequencyProperty.java (hunk 5 above)
Comment (mgmax) [reply src/main/java/de/thomas_oster/liblasercut/FloatMinMaxPowerSpeedFrequencyProperty.java:34]: According to my first quick check, everything else (load and save device settings) seems to work.

The default power value 0 is correct and same as for the Epilog driver. (In the above discussion, "0 vs 20" referred to raster padding, not power.)

Regarding usability, you could possibly improve the editing of "min power" (in some future version, not in this PR). Currently, the default initial value is unlogical (min power = 10 > power = 0). When editing min power to e.g. 11 it is reset to 0, which technically makes sense but may be confusing to the user who wants to enter "min power" first and then "power" second. You could remove the limiting of "min power" from the Property class and instead just limit it in the driver (silently, or maybe with a warning message).

Comment (jnweiger) [reply src/main/java/de/thomas_oster/liblasercut/FloatMinMaxPowerSpeedFrequencyProperty.java:34]: @kkaempf is it acceptable what @mgmax suggests?
I'd like to get this merged. This blocks us from using visicut with thunderlaser.
(my private build always comes up with an empty settings panel for unknown reasons)

**Comment by mgmax** [comment]
I see that the driver converts speeds  0-100%  to 0-1000mm/s. Your driver has settings for "Max vector cutting speed (mm/s)" and "Max vector move speed (mm/s)" which currently have no effect. Do all Ruida machines have a limit of 100% = 1000 mm/s? 

If yes, these settings should probably be removed.
To do so, remove everything related to `MaxVector...` and `MAX_VECTOR_...` except for the one line where the class attribute is declared. To avoid that importing old settings fails, do not remove the attribute but mark it as `@Deprecated transient` , as in
https://github.com/t-oster/LibLaserCut/blob/bc3f41385535869d6c47f158ddb7fdb48a2997dd/src/main/java/de/thomas_oster/liblasercut/drivers/LaserToolsTechnicsCutter.java#L238-L244

If no, then the conversion should depend on the configured speed. `speed_mmps = speed_percent * max_speed / 100`

**Comment by kkaempf** [comment]
Hmm, this issue started with "fix Ruida rasterizable" and has meanwhile grown to a generic (and helpful ! Don't get me wrong here 😉 ) Ruida driver improvement one.

I'd rather see this splitted into multiple issues and fix problems in separated PRs.

**Comment by mgmax** [comment]
Good suggestion!
The leftover issue was detached to https://github.com/t-oster/LibLaserCut/issues/190 .
Furthermore, you could look into the (GUI) usability of "min power" as discussed before.
